FROM alpine:3.23.2 AS builder

ARG VALKEY_VERSION=9.0.1
WORKDIR /home/valkey

RUN apk add --no-cache --virtual .build-deps \
	git \
	coreutils \
	linux-headers \
	musl-dev \
	openssl-dev \
	gcc \
	curl \
	make \
	&& curl -L https://github.com/valkey-io/valkey/archive/refs/tags/${VALKEY_VERSION}.tar.gz -o valkey.tar.gz \
	&& tar -xzf valkey.tar.gz --strip-components=1 \
	&& make PREFIX=/usr BUILD_TLS=yes \
	&& make install BUILD_TLS=yes PREFIX=/home/valkey/build

FROM alpine:3.23.2 AS valkey

RUN apk add --no-cache \
	openssl \
	ca-certificates \
	coreutils \
	&& addgroup -S valkey -g 1009 \
	&& adduser -S -G valkey valkey -u 1009 \
	&& mkdir /etc/valkey \
	&& chown valkey:valkey /etc/valkey \
	&& mkdir /var/lib/valkey \
	&& chown valkey:valkey /var/lib/valkey

COPY --from=builder /home/valkey/build/ /usr/

USER valkey
